version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    environment:
      - WEBHOOK_URL=https://a59972d57213.ngrok-free.app
      - N8N_SECURE_COOKIE=false
      - N8N_PORT=${N8N_PORT}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    env_file:
      - .env
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: always
